Created regression test for DeletionMixin with lazy success_url value
 - Raises AttributeError: '__proxy__' object has no attribute 'decode'
   in Python 3.2 and later